Support PKCS#8 standard keys from Zero trust Identity Service
SAP/cloud-security-services-integration-library pull request #1528
Opened 2024-05-03 11:29 UTC by liga-oz

2024-05-03 12:37 UTC, finkmanAtSap approved these changes
Nice work!

2024-05-13 12:18 UTC, finkmanAtSap requested changes
I think I understand the intention of the PR now and you can consider it approved. I just added some minor comments that you may or may not want to implement.

2024-05-13 12:18 UTC, finkmanAtSap commented on java-api/src/main/java/com/sap/cloud/security/config/ClientIdentity.java
> +	default Certificate[] getCertificateChain() {
should be @Nullable like the remaining getters?

2024-05-13 12:18 UTC, finkmanAtSap commented on java-api/src/main/java/com/sap/cloud/security/config/ClientIdentity.java
> +	default PrivateKey getPrivateKey() {
should be @Nullable like the remaining getters?

2024-05-13 12:18 UTC, finkmanAtSap commented on java-api/src/main/java/com/sap/cloud/security/config/ClientIdentity.java
> +		return hasValue(getCertificate()) && hasValue(
the formatting looks weird, can we put the two different combinations on one line each maybe?

2024-05-13 12:18 UTC, finkmanAtSap commented on token-client/src/main/java/com/sap/cloud/security/mtls/SSLContextFactory.java
> +		try {
I think this is try/catch is redundant because the same checks are performed inside createKeyStore which is the first statement following these lines

2024-05-13 12:18 UTC, finkmanAtSap commented on token-client/src/main/java/com/sap/cloud/security/mtls/SSLContextFactory.java
> +		if (pemPrivateKey != null) {
Is it intentionally not an *else if*?

My suggestion would be:
* remove both try/catch blocks from parent functions and inside _getPrivateKey_:
   * Call getPrivateKey() and getCertificateChain().
   * If both not null, use the PrivateKey instance directly if possible or create PrivateKey instance from it as done in line 175.
   * Else build PrivateKey from getKey() if getKey() and getCertificate() both not null/empty
   * Return PrivateKey if it was built in previous lines or throw the exception if not

2024-05-14 11:11 UTC, finkmanAtSap approved these changes
Nice!

I'm happy with the changes but I have one more thought: We could have also moved the new logic into the ClientCertificate class which has one constructor for String-based certificate+key and one constructor for a PrivateKey/Certificate[] combination. Internally, the class could compute the missing parameters from the provided ones, such that the getters are all non-null, no matter what the instance was constructed from.
In the SSLContextFactory, one could then always call getPrivateKey and getCertificateChain without having to differentiate between the formats.
Not sure which alternative is better but in the second option, I think it is nicer that the support of different certificate formats/classes would be isolated in the ClientCertificate class and not spread across modules.

2024-05-14 12:06 UTC, liga-oz commented
> Nice!
> 
> I'm happy with the changes but I have one more thought: We could have also moved the new logic into the ClientCertificate class which has one constructor for String-based certificate+key and one constructor for a PrivateKey/Certificate[] combination. Internally, the class could compute the missing parameters from the provided ones, such that the getters are all non-null, no matter what the instance was constructed from. In the SSLContextFactory, one could then always call getPrivateKey and getCertificateChain without having to differentiate between the formats. Not sure which alternative is better but in the second option, I think it is nicer that the support of different certificate formats/classes would be isolated in the ClientCertificate class and not spread across modules.

the idea is quite good, but that would be quite a big chunk of logic that goes into certificate class and it would be a bit bigger refactoring and I would say too big for this PR. I'll create a BLI for this as it's not that high Prio but good to have thing 👍🏻

2024-05-14 12:39 UTC, merged