[work in progress] Rework samples
SAP/cloud-security-services-integration-library pull request #1632
Opened 2024-10-14 14:39 UTC by kuntzed

To improve the readability of the samples applications we do some small refactorings. This includes implementation and configuration harmonisations. Furthermore, additional examples for k8b are added and the instructions (README files) for the samples are rewritten.

2024-10-15 09:32 UTC, finkmanAtSap approved these changes

2024-10-15 09:32 UTC, finkmanAtSap commented on samples/java-security-usage/README.md
Nice! This should be much smoother now for customers.

2024-10-15 09:35 UTC, finkmanAtSap requested changes
I think the E2E tests might be failing in the Github actions workflow because the `maven.compiler.target` or `maven.compiler.source` option has been replaced by `maven.compiler.release`?

2024-10-16 11:27 UTC, kuntzed commented on samples/java-security-usage/README.md
> +This can be done in the SAP BTP Cockpit or using the btp CLI.
There are two official names for this CLI:
1. SAP BTP Command Line Interface
2. btp CLI

2024-10-16 11:41 UTC, kuntzed commented on docs/HowToFetchToken.md
I would prefer not to force users to pull together the instructions from several places. But I wonder if we can remove this postman collection stuff. Part of the instructions require the command-line anyway. I see two options:
1. Reduce the instructions two the curl commands and additionally provide a link to the official documentation
2. Remove the complete file and just add the required commands directly to the README files.

What do you think?

2024-10-16 11:51 UTC, kuntzed commented on samples/java-security-usage/README.md
> +</details>
I prefer self-contained instructions. If you really have a strong opinion here, then I could remove the detailed instructions. But I would like to keep mentioning the two ways of assigning the role collection.

2024-10-16 11:51 UTC, kuntzed commented on samples/java-security-usage/README.md
Thanks.

2024-10-16 15:01 UTC, finkmanAtSap commented on samples/java-security-usage/README.md
> +This can be done in the SAP BTP Cockpit or using the btp CLI.
Aaaah, I see. Thought it was a typo. Nevermind then if it's the official name.

2024-10-16 15:03 UTC, finkmanAtSap commented on samples/java-security-usage/README.md
> +</details>
We can leave it in but I don' think we'll manage to maintain it if something changes in the UI.

2024-10-16 15:22 UTC, kuntzed commented on samples/java-security-usage/README.md
> +</details>
That's true. But besides that not being very likely, we have the links to help.sap.com in place as a fallback.

2024-10-16 15:25 UTC, finkmanAtSap commented on docs/HowToFetchToken.md
Option 1 sounds good to me if you can work in the OTP code into the curl scripts as required.

2024-10-18 09:56 UTC, kuntzed commented on docs/HowToFetchToken.md
Ok, will do

2024-10-30 13:31 UTC, finkmanAtSap approved these changes

2024-10-30 13:38 UTC, merged